import { BibliographyEntry, BookProject } from '../types';

export const DEFAULT_SAMPLE_BIBLIOGRAPHY: BibliographyEntry[] = [
  {
    id: 'bib-sample-1',
    citeKey: 'smith2024neural',
    entryType: 'article',
    title: 'Neural Manuscript Synthesis and Computational Book Layouts',
    author: 'Smith, John and Doe, Jane',
    year: '2024',
    journalOrPublisher: 'Journal of Digital Publishing & Design',
    volume: '15',
    numberOrIssue: '2',
    pages: '104--122',
    doi: '10.1016/j.jdp.2024.02.001',
    url: 'https://doi.org/10.1016/j.jdp.2024.02.001',
    note: 'Seminal paper on automated typesetting engines.'
  },
  {
    id: 'bib-sample-2',
    citeKey: 'knuth1984texbook',
    entryType: 'book',
    title: 'The TeXbook: A Complete Guide to Computer Typesetting',
    author: 'Knuth, Donald E.',
    year: '1984',
    journalOrPublisher: 'Addison-Wesley Professional',
    pages: '1--483',
    url: 'https://www.ctan.org/pkg/texbook',
    note: 'Foundational manual on mathematical typography.'
  },
  {
    id: 'bib-sample-3',
    citeKey: 'vaswani2017attention',
    entryType: 'inproceedings',
    title: 'Attention Is All You Need',
    author: 'Vaswani, Ashish and Shazeer, Noam and Parmar, Niki and Uszkoreit, Jakob and Jones, Llion and Gomez, Aidan N and Kaiser, Łukasz and Polosukhin, Illia',
    year: '2017',
    journalOrPublisher: 'Advances in Neural Information Processing Systems (NeurIPS)',
    volume: '30',
    pages: '5998--6008',
    url: 'https://arxiv.org/abs/1706.03762'
  }
];

/**
 * Convert a list of BibliographyEntry items into a formatted standard BibTeX string (.bib)
 */
export function generateBibTeXString(entries: BibliographyEntry[]): string {
  if (!entries || entries.length === 0) {
    return '% No bibliography entries provided.\n';
  }

  let bibtex = `% ==========================================================\n`;
  bibtex += `% Generated by PressCraft Studio BibTeX / LaTeX Engine\n`;
  bibtex += `% Total References: ${entries.length}\n`;
  bibtex += `% ==========================================================\n\n`;

  entries.forEach((entry) => {
    const type = (entry.entryType || 'article').toLowerCase();
    const key = entry.citeKey.trim() || `ref_${entry.id}`;

    bibtex += `@${type}{${key},\n`;
    if (entry.title) bibtex += `  title = {${entry.title}},\n`;
    if (entry.author) bibtex += `  author = {${entry.author}},\n`;
    if (entry.year) bibtex += `  year = {${entry.year}},\n`;

    if (type === 'article') {
      if (entry.journalOrPublisher) bibtex += `  journal = {${entry.journalOrPublisher}},\n`;
      if (entry.volume) bibtex += `  volume = {${entry.volume}},\n`;
      if (entry.numberOrIssue) bibtex += `  number = {${entry.numberOrIssue}},\n`;
    } else if (type === 'book') {
      if (entry.journalOrPublisher) bibtex += `  publisher = {${entry.journalOrPublisher}},\n`;
    } else if (type === 'inproceedings') {
      if (entry.journalOrPublisher) bibtex += `  booktitle = {${entry.journalOrPublisher}},\n`;
    } else {
      if (entry.journalOrPublisher) bibtex += `  publisher = {${entry.journalOrPublisher}},\n`;
    }

    if (entry.pages) bibtex += `  pages = {${entry.pages}},\n`;
    if (entry.doi) bibtex += `  doi = {${entry.doi}},\n`;
    if (entry.url) bibtex += `  url = {${entry.url}},\n`;
    if (entry.note) bibtex += `  note = {${entry.note}},\n`;

    // Remove trailing comma if needed, close brace
    bibtex = bibtex.replace(/,\n$/, '\n');
    bibtex += `}\n\n`;
  });

  return bibtex;
}

/**
 * Generate a complete standalone LaTeX document (.tex) incorporating project title, chapters, and bibliography
 */
export function generateFullLaTeXDocument(project: BookProject): string {
  const entries = project.bibliography && project.bibliography.length > 0
    ? project.bibliography
    : DEFAULT_SAMPLE_BIBLIOGRAPHY;

  let tex = `% ==========================================================\n`;
  tex += `% PressCraft Studio LaTeX Publishing Export\n`;
  tex += `% Book Title: ${project.title}\n`;
  tex += `% Author: ${project.author}\n`;
  tex += `% Category: ${project.category}\n`;
  tex += `% ==========================================================\n\n`;

  tex += `\\documentclass[11pt,a4paper,twoside]{book}\n`;
  tex += `\\usepackage[utf8]{inputenc}\n`;
  tex += `\\usepackage[margin=1in]{geometry}\n`;
  tex += `\\usepackage{amsmath,amssymb,amsfonts}\n`;
  tex += `\\usepackage{graphicx}\n`;
  tex += `\\usepackage{hyperref}\n`;
  tex += `\\usepackage{cite}\n`;
  tex += `\\usepackage{microtype}\n\n`;

  tex += `\\title{\\Huge \\bfseries ${escapeLaTeX(project.title)} \\\\ \\large ${escapeLaTeX(project.subtitle || '')}}\n`;
  tex += `\\author{\\Large ${escapeLaTeX(project.author)}}\n`;
  tex += `\\date{\\today}\n\n`;

  tex += `\\begin{document}\n\n`;
  tex += `\\maketitle\n\n`;

  if (project.frontMatter.includeTOC) {
    tex += `\\tableofcontents\n\\cleardoublepage\n\n`;
  }

  // Iterate Chapters
  project.chapters.forEach((ch, idx) => {
    tex += `\\chapter{${escapeLaTeX(ch.title)}}\n`;
    if (ch.subtitle) {
      tex += `\\subsubsection*{${escapeLaTeX(ch.subtitle)}}\n`;
    }
    tex += `\n`;

    ch.blocks.forEach((block) => {
      if (block.type === 'heading') {
        tex += `\\section{${escapeLaTeX(block.text)}}\n\n`;
      } else if (block.type === 'subheading') {
        tex += `\\subsection{${escapeLaTeX(block.text)}}\n\n`;
      } else if (block.type === 'latex') {
        tex += `\\begin{equation}\n  ${block.latexFormula || block.text}\n\\end{equation}\n\n`;
      } else if (block.type === 'quote') {
        tex += `\\begin{quote}\n  ${escapeLaTeX(block.text)}\n\\end{quote}\n\n`;
      } else if (block.type === 'code') {
        tex += `\\begin{verbatim}\n${block.codeSnippet || block.text}\n\\end{verbatim}\n\n`;
      } else {
        if (block.text && block.text.trim()) {
          tex += `${escapeLaTeX(block.text)}\n\n`;
        }
      }
    });

    tex += `\n`;
  });

  // Bibliography Section
  tex += `% ==========================================================\n`;
  tex += `% BIBLIOGRAPHY SECTION\n`;
  tex += `% ==========================================================\n\n`;
  tex += `\\begin{thebibliography}{99}\n`;

  entries.forEach((e) => {
    const key = e.citeKey.trim() || `ref_${e.id}`;
    const authorStr = escapeLaTeX(e.author || 'Anonymous');
    const titleStr = escapeLaTeX(e.title || 'Untitled');
    const pubStr = e.journalOrPublisher ? `\\textit{${escapeLaTeX(e.journalOrPublisher)}}` : '';
    const yearStr = e.year ? `(${e.year})` : '';
    const volStr = e.volume ? `Vol. ${e.volume}` : '';
    const pagesStr = e.pages ? `pp. ${e.pages}` : '';

    tex += `\\bibitem{${key}}\n`;
    tex += '  ' + authorStr + ', ``' + titleStr + "'', " + pubStr + ' ' + volStr + ' ' + pagesStr + ' ' + yearStr + '.\n\n';
  });

  tex += `\\end{thebibliography}\n\n`;
  tex += `\\end{document}\n`;

  return tex;
}

/**
 * Escape special LaTeX characters
 */
function escapeLaTeX(str: string): string {
  if (!str) return '';
  return str
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}
