import { describe,expect,it } from 'vitest';
import fs from 'node:fs';
import { createEmptyBookProject } from '../data/createEmptyBookProject';
import { cloneParagraphPreset, findPreviousParagraphContext, resolveParagraphFormatting } from './paragraphFormatting';
import { createSceneBreakBlock, DEFAULT_SCENE_BREAK, resolveSceneBreak, sanitizeSceneBreakText, sceneBreakHtml, sceneBreakMark } from './sceneBreak';

describe('semantic scene breaks',()=>{
 it('creates deterministic professional metadata with unique IDs',()=>{const a=createSceneBreakBlock(),b=createSceneBreakBlock();expect(a).toMatchObject({type:'scene-break',text:'',sceneBreak:DEFAULT_SCENE_BREAK});expect(a.id).not.toBe(b.id);});
 it('resolves all built-in styles',()=>{for(const style of ['asterisms','dots','rule','ornament','whitespace'] as const){const b=createSceneBreakBlock();b.sceneBreak!.style=style;expect(resolveSceneBreak(b).style).toBe(style);}expect(sceneBreakMark({...DEFAULT_SCENE_BREAK})).toBe('* * *');});
 it('sanitizes and length-limits custom text',()=>{expect(sanitizeSceneBreakText('<script>alert(1)</script>')).not.toContain('<');expect(sanitizeSceneBreakText('x'.repeat(50))).toHaveLength(24);});
 it('never converts punctuation paragraphs',()=>{const p={id:'p',type:'paragraph' as const,text:'***'};expect(p).toEqual({id:'p',type:'paragraph',text:'***'});});
 it('exports safe semantic HTML without editor labels',()=>{const html=sceneBreakHtml(createSceneBreakBlock());expect(html).toContain('class="scene-break"');expect(html).not.toContain('Scene Break Settings');});
 it('suppresses the next paragraph indent but preserves side indents',()=>{const project=createEmptyBookProject(),t={...project.typography!,paragraphs:{...cloneParagraphPreset('fiction-standard'),leftIndentPt:9,rightIndentPt:7}};const scene=createSceneBreakBlock(),p={id:'p',type:'paragraph' as const,text:'Next'};const r=resolveParagraphFormatting(p,scene,2,t);expect(r).toMatchObject({firstLineIndentPt:0,leftIndentPt:9,rightIndentPt:7});});
 it('allows an explicit next-paragraph override to win',()=>{const project=createEmptyBookProject(),t={...project.typography!,paragraphs:cloneParagraphPreset('fiction-standard')};const p={id:'p',type:'paragraph' as const,text:'Next',paragraphFormatting:{mode:'first-line' as const,firstLineIndentPt:31}};expect(resolveParagraphFormatting(p,createSceneBreakBlock(),2,t).firstLineIndentPt).toBe(31);});
 it('skips captions but stops scene context at headings and images',()=>{const scene=createSceneBreakBlock(),caption={id:'c',type:'caption' as const,text:'caption'},heading={id:'h',type:'heading' as const,text:'Heading'},image={id:'i',type:'image' as const,text:''},p={id:'p',type:'paragraph' as const,text:'Body'};expect(findPreviousParagraphContext([scene,caption,p],2)?.type).toBe('scene-break');expect(findPreviousParagraphContext([scene,heading,p],2)?.type).toBe('heading');expect(findPreviousParagraphContext([scene,image,p],2)?.type).toBe('image');});
 it('has explicit editor and renderer branches without textarea fallback',()=>{const editor=fs.readFileSync('src/components/EditorCanvas.tsx','utf8'),focus=fs.readFileSync('src/components/FocusMode.tsx','utf8'),preview=fs.readFileSync('src/components/PrintPreviewModal.tsx','utf8');expect(editor).toContain(`block.type === 'scene-break'`);expect(editor).toContain('Insert Scene Break');expect(focus).toContain(`block.type==='scene-break'`);expect(preview).toContain(`block.type==='scene-break'`);});
 it('maps PDF, HTML, EPUB, DOCX and Markdown exports',()=>{const source=fs.readFileSync('src/lib/exportUtils.ts','utf8');expect(source.match(/sceneBreakHtml/g)?.length).toBeGreaterThanOrEqual(3);expect(source).toContain(`block.type === 'scene-break'`);expect(source).toContain('keepNext:s.keepWithNext');expect(source).toContain(`sceneBreakMark(resolveSceneBreak(block))`);});
});
